Repository jameslamb/pydistcheck, pull requests merged in 2025-01, with the labels that each got.

#289 [ci] add codespell
  .github/CODE_OF_CONDUCT.md
  .pre-commit-config.yaml
  docs/how-to-test-a-python-distribution.rst
  src/pydistcheck/distribution_summary.py
Labels: maintenance

#290 Correctly vendor `delocate` license in wheels
  LICENSE
  MANIFEST.in
  pyproject.toml
  src/pydistcheck/file_utils.py
Labels: fix

#291 [ci] update versions of CI dependencies
  .pre-commit-config.yaml
  docs/env.yml
Labels: maintenance

#292 [docs] add 'cph' and 'validate-pyproject' to docs (fixes #283)
  .pre-commit-config.yaml
  docs/how-to-test-a-python-distribution.rst
Labels: doc

#294 [docs] fix formatting
  docs/how-to-test-a-python-distribution.rst
Labels: doc

#295 [ci] add CMake linting/formatting, update `pre-commit` hooks, re-arrange modules
  .cmake-format.yaml
  .pre-commit-config.yaml
  .yamllint.yaml
  pyproject.toml
  src/pydistcheck/_checks.py
  src/pydistcheck/_config.py
  src/pydistcheck/_distribution_summary.py
  src/pydistcheck/_file_utils.py
  src/pydistcheck/_inspect.py
  src/pydistcheck/_shared_lib_utils.py
  src/pydistcheck/_utils.py
  src/pydistcheck/cli.py
  tests/data/baseballmetrics/CMakeLists.txt
  tests/test_checks.py
  tests/test_config.py
  tests/test_distribution_summary.py
  tests/test_docs.py
  tests/test_utils.py
Labels: maintenance

#296 Show 3 digits instead of 1 in file size strings.
  src/pydistcheck/_utils.py
  tests/test_cli.py
  tests/test_utils.py
Labels: enhancement
