Repository jameslamb/pydistcheck, pull requests merged in 2025-03, with the labels that each got.

#310 Ignore `radr://5614542` remnant debug symbol for binaries stripped via Apple's `strip` utility
  src/pydistcheck/_shared_lib_utils.py
  tests/test_shared_lib_utils.py
Labels: fix

#309 Switch to `latin1` encoding for binary output for debug symbol checks in compiled objects
  Makefile
  src/pydistcheck/_shared_lib_utils.py
  tests/test_cli.py
  tests/test_shared_lib_utils.py
Labels: fix

#312 [ci] [docs] add link-checking in CI (fixes #293)
  .github/workflows/check-docs.yml
  .gitignore
  .lycheeignore
  .pre-commit-config.yaml
  .readthedocs.yaml
  docs/_static/defaults.toml
  docs/check-reference.rst
  docs/conf.py
  docs/how-to-test-a-python-distribution.rst
  docs/installation.rst
  src/pydistcheck/_config.py
Labels: doc

#313 release v0.9.1
  src/pydistcheck/__init__.py
Labels: maintenance

#314 bump development version
  bin/create-version-bump-pr
  src/pydistcheck/__init__.py
Labels: maintenance
